"use client";

import { useState } from "react";
import { Lock, LockOpen, Download, Star, Copy, Check } from "lucide-react";
import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

interface BriefCardProps {
  id: string;
  title: string;
  hook: string;
  script_body: string;
  cta: string;
  visual_cue: string;
  viralScore: number;
  thumbnailUrl: string;
  isLocked?: boolean;
  onUnlock?: () => void;
  onDownload?: () => void;
}

export function BriefCard({
  title,
  hook,
  script_body,
  cta,
  visual_cue,
  viralScore,
  thumbnailUrl,
  isLocked = false,
  onUnlock,
  onDownload,
}: BriefCardProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    const text = `🎬 PROJECT: ${title}\n⭐ VIRAL SCORE: ${viralScore}/10\n\n🪝 HOOK:\n"${hook}"\n\n📝 SCRIPT:\n${script_body}\n\n📢 CTA: ${cta}\n\n🎨 VISUAL: ${visual_cue}\n\nGenerated by TubeToTikTok`;
    
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy text: ", err);
    }
  };

  return (
    <div
      className={cn(
        "group relative flex flex-col overflow-hidden rounded-2xl bg-card-dark border transition-all duration-300 break-inside-avoid",
        isLocked
          ? "border-border-dark"
          : "border-primary/50 shadow-[0_0_30px_rgba(242,13,85,0.15)] ring-1 ring-primary/20"
      )}
    >
      {/* Badge */}
      <div className="absolute top-4 right-4 z-10">
        <span
          className={cn(
            "inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-bold text-white shadow-lg",
            isLocked ? "bg-card-dark border border-border-dark" : "bg-primary shadow-[0_0_10px_rgba(242,13,85,0.5)]"
          )}
        >
          {isLocked ? (
            <>
              <Lock className="w-3 h-3" /> Locked
            </>
          ) : (
            <>
              <LockOpen className="w-3 h-3" /> Unlocked
            </>
          )}
        </span>
      </div>

      {/* Content Container */}
      <div className={cn("flex flex-col h-full", isLocked && "relative")}>
        {/* Thumbnail Area */}
        <div className="relative w-full aspect-video overflow-hidden">
          <div
            className={cn(
              "absolute inset-0 bg-cover bg-center transition-transform duration-700 ease-out",
              !isLocked && "group-hover:scale-105",
              isLocked && "blur-md opacity-30 scale-110"
            )}
            style={{ backgroundImage: `url('${thumbnailUrl}')` }}
          />
          {!isLocked && (
            <div className="absolute inset-0 bg-gradient-to-t from-card-dark via-transparent to-transparent" />
          )}
          
          {!isLocked && (
            <div className="absolute bottom-4 left-4 right-4 flex justify-between items-end">
              <div className="bg-black/60 backdrop-blur-sm px-2 py-1 rounded text-xs font-medium text-white">
                00:45
              </div>
            </div>
          )}
        </div>

        {/* Text Area */}
        <div className={cn("flex flex-col gap-4 p-5 md:p-6 bg-card-dark flex-1", isLocked && "blur-sm select-none pointer-events-none")}>
          <div>
            <h3 className="text-xl font-bold text-white mb-1 leading-snug">
              {title}
            </h3>
            <div className="flex items-center gap-2 text-sm text-text-muted">
              <Star className="w-4 h-4 text-yellow-500 fill-yellow-500" />
              <span className="text-white font-medium">{viralScore}/10 Viral Score</span>
            </div>
          </div>

          <div className="space-y-4">
            <div className="bg-background-dark/50 p-3 rounded-lg border border-border-dark">
              <p className="text-xs uppercase tracking-wider font-bold text-text-muted mb-1">Hook</p>
              <p className="text-white text-sm font-medium leading-relaxed">
              &quot;{hook}&quot;
            </p>
            </div>
            <div className="bg-background-dark/50 p-3 rounded-lg border border-border-dark">
              <p className="text-xs uppercase tracking-wider font-bold text-text-muted mb-1">Script Body</p>
              <p className="text-text-muted text-sm leading-relaxed whitespace-pre-wrap">
                {script_body}
              </p>
            </div>
            <div className="bg-background-dark/50 p-3 rounded-lg border border-border-dark">
              <p className="text-xs uppercase tracking-wider font-bold text-text-muted mb-1">Call to Action</p>
              <p className="text-text-muted text-sm font-medium italic">
                &quot;{cta}&quot;
              </p>
            </div>
            <div className="bg-background-dark/50 p-3 rounded-lg border border-border-dark">
              <p className="text-xs uppercase tracking-wider font-bold text-text-muted mb-1">Visual Cue</p>
              <p className="text-text-muted text-sm italic">
                {visual_cue}
              </p>
            </div>
          </div>

          <div className="pt-2 flex gap-3 mt-auto">
            <button
              onClick={handleCopy}
              disabled={isLocked}
              className={cn(
                "flex-1 flex cursor-pointer items-center justify-center gap-2 rounded-lg h-10 px-4 transition-all border font-bold text-sm",
                copied 
                  ? "bg-green-500/10 border-green-500/50 text-green-500" 
                  : "bg-white/5 border-white/10 text-white hover:bg-white/10"
              )}
            >
              {copied ? (
                <>
                  <Check className="w-4 h-4" />
                  Copied
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" />
                  Copy
                </>
              )}
            </button>
            <button
              onClick={onDownload}
              className="flex-1 flex cursor-pointer items-center justify-center gap-2 rounded-lg h-10 px-4 bg-primary text-white text-sm font-bold shadow-[0_0_10px_rgba(242,13,85,0.3)] hover:bg-primary-dark transition-all"
            >
              <Download className="w-4 h-4" />
              Download
            </button>
          </div>
        </div>

        {/* Lock Overlay */}
        {isLocked && (
          <div className="absolute inset-0 z-20 flex flex-col items-center justify-center bg-background-dark/60 backdrop-blur-[6px] p-6 text-center">
            <div className="mb-4 rounded-full bg-card-dark p-4 shadow-xl border border-border-dark group-hover:scale-110 transition-transform duration-300">
              <Lock className="w-8 h-8 text-primary drop-shadow-[0_0_8px_rgba(242,13,85,0.8)]" />
            </div>
            <h3 className="text-white text-xl font-bold mb-2">{title}</h3>
            <p className="text-text-muted text-sm mb-6 max-w-[200px]">
              High potential viral clip detected. Unlock to see the hook.
            </p>
            <button
              onClick={onUnlock}
              className="flex cursor-pointer items-center justify-center rounded-lg h-10 px-6 bg-white text-black text-sm font-bold hover:bg-gray-200 transition-colors shadow-lg transform hover:-translate-y-0.5"
            >
              Sign Up to Reveal
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
